local M = {}

local state = {
  actions = {},
}

local function file_has_content(path)
  local stat = vim.uv.fs_stat(path)
  return stat ~= nil and stat.type == 'file' and stat.size > 0
end

local function tutor_paths()
  local root = vim.fs.joinpath(vim.fn.stdpath 'data', 'kickstart-tutor')
  local java_root = vim.fs.joinpath(root, 'java-drill')
  local java_src = vim.fs.joinpath(java_root, 'src', 'main', 'java', 'com', 'kickstart', 'tutor')
  local java_test = vim.fs.joinpath(java_root, 'src', 'test', 'java', 'com', 'kickstart', 'tutor')

  return {
    root = root,
    readme = vim.fs.joinpath(root, 'README.md'),
    movement = vim.fs.joinpath(root, '00-movement.txt'),
    editing = vim.fs.joinpath(root, '10-editing.txt'),
    notes = vim.fs.joinpath(root, 'notes', 'navigation-notes.md'),
    git_demo = vim.fs.joinpath(root, '40-git-demo.txt'),
    java_root = java_root,
    pom = vim.fs.joinpath(java_root, 'pom.xml'),
    java_app = vim.fs.joinpath(java_src, 'App.java'),
    java_greeter = vim.fs.joinpath(java_src, 'Greeter.java'),
    java_test = vim.fs.joinpath(java_test, 'GreeterTest.java'),
  }
end

local function split_lines(text)
  return vim.split(text:gsub('\r\n', '\n'), '\n', { plain = true, trimempty = false })
end

local function write_file(path, text)
  vim.fn.mkdir(vim.fs.dirname(path), 'p')
  vim.fn.writefile(split_lines(text), path)
end

local function run(cmd, cwd)
  local result = vim.system(cmd, { cwd = cwd, text = true }):wait()
  if result.code ~= 0 then
    local message = result.stderr ~= '' and result.stderr or result.stdout
    error(string.format('Command failed: %s\n%s', table.concat(cmd, ' '), message))
  end
  return result
end

local function build_workspace()
  local paths = tutor_paths()

  vim.fn.delete(paths.root, 'rf')
  vim.fn.mkdir(paths.root, 'p')

  write_file(paths.readme, [[# Kickstart Tutor Workspace

This workspace is generated by `:KickstartTutor`.

Use it for:
- motion drills in `00-movement.txt`
- editing drills in `10-editing.txt`
- project navigation from this root
- git hunk practice in `40-git-demo.txt`
- Java navigation, refactors, tests, and debugging in `java-drill/`

Search targets:
- clockwork
- ember-fox
- terminal-pro
- Greeter
]])

  write_file(paths.movement, [[KICKSTART TUTOR: MOVEMENT

Warm-up punctuation runway
alpha.beta/gamma:delta;epsilon,zeta
omega.beta/gamma:delta;epsilon,zeta

Repeat targets
find-this find-this find-this find-this
land-here; then-repeat; then-repeat; then-repeat;

Matching pairs
if (ready && (count > 2)) { call("alpha", [1, 2, 3]); }
map = { one: [start, middle, finish], two: (left + right) }

Word search targets
Greeter greeter Greeter GREETER
terminal-pro terminal-pro terminal-pro

Marks runway
MARK-A
walk past these lines
line 17
line 18
line 19
MARK-B

Jumplist runway
1 one
2 two
3 three
4 four
5 five
6 six
7 seven
8 eight
9 nine
10 ten
11 eleven
12 twelve
]])

  write_file(paths.editing, [[KICKSTART TUTOR: EDITING

Change inside
quote_1 = "replace this phrase"
quote_2 = "replace this phrase"
quote_3 = "replace this phrase"

Delete around
delete_me = call(alpha, beta, gamma)
delete_me_too = [red, green, blue]

Repeatable edits
name = alpha-run
name = beta-run
name = gamma-run
name = delta-run

Registers
source_word = phoenix
slot_one =
slot_two =

Macros
TODO 1 - pending
TODO 2 - pending
TODO 3 - pending
TODO 4 - pending

mini.surround targets
surround word
second target
html chunk
]])

  write_file(paths.notes, [[# Navigation Notes

This file exists so Telescope and Neo-tree have more than one path to explore.

Keywords to search with `live_grep`:
- clockwork
- ember-fox
- terminal-pro
- Greeter

Suggested drills:
- find `clockwork`
- open the Java app entrypoint
- jump back with the jumplist
]])

  write_file(paths.git_demo, [[status = pending
owner = neo
color = blue
checkpoint = cold
line 5 stays still
line 6 stays still
line 7 stays still
line 8 stays still
line 9 stays still
line 10 stays still
priority = medium
signal = low
line 13 stays still
line 14 stays still
line 15 stays still
note = keep this stable
]])

  write_file(paths.pom, [[<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.kickstart</groupId>
  <artifactId>tutor</artifactId>
  <version>1.0-SNAPSHOT</version>

  <properties>
    <maven.compiler.release>21</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <junit.version>5.12.2</junit.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.5.3</version>
      </plugin>
    </plugins>
  </build>
</project>
]])

  write_file(paths.java_greeter, [[package com.kickstart.tutor;

public class Greeter {
  private final String prefix;

  public Greeter(String prefix) {
    this.prefix = prefix;
  }

  public String messageFor(String name) {
    return prefix + " says hello to " + name;
  }

  public String enthusiasticMessageFor(String name) {
    return messageFor(name).toUpperCase();
  }
}
]])

  write_file(paths.java_app, [[package com.kickstart.tutor;

import java.util.ArrayList;

public class App {
  public static void main(String[] args) {
    Greeter greeter = new Greeter("Kickstart Tutor");
    System.out.println(greeter.messageFor("terminal-pro"));
  }

  public String banner() {
    return "clockwork ember-fox";
  }
}
]])

  write_file(paths.java_test, [[package com.kickstart.tutor;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class GreeterTest {
  @Test
  void buildsGreeting() {
    Greeter greeter = new Greeter("Tutor");
    assertEquals("Tutor says hello to terminal-pro", greeter.messageFor("terminal-pro"));
  }

  @Test
  void buildsEnthusiasticGreeting() {
    Greeter greeter = new Greeter("Tutor");
    assertEquals("TUTOR SAYS HELLO TO TERMINAL-PRO", greeter.enthusiasticMessageFor("terminal-pro"));
  }
}
]])

  run({ 'git', 'init', '-b', 'main' }, paths.root)
  run({ 'git', 'config', 'user.name', 'Kickstart Tutor' }, paths.root)
  run({ 'git', 'config', 'user.email', 'tutor@example.invalid' }, paths.root)
  run({ 'git', 'add', '.' }, paths.root)
  run({ 'git', 'commit', '-m', 'Initial tutorial workspace' }, paths.root)

  write_file(paths.git_demo, [[status = ready
owner = neo
color = amber
checkpoint = warm
line 5 stays still
line 6 stays still
line 7 stays still
line 8 stays still
line 9 stays still
line 10 stays still
priority = high
signal = focused
line 13 stays still
line 14 stays still
line 15 stays still
note = preview before staging
]])

  return paths
end

local function ensure_workspace()
  local paths = tutor_paths()
  if file_has_content(paths.readme)
    and file_has_content(paths.movement)
    and file_has_content(paths.editing)
    and file_has_content(paths.git_demo)
    and file_has_content(paths.java_app)
    and vim.uv.fs_stat(vim.fs.joinpath(paths.root, '.git'))
  then
    return paths
  end
  return build_workspace()
end

local function open_file(path, cwd)
  local paths = ensure_workspace()
  if not file_has_content(path) then
    build_workspace()
  end
  vim.cmd.tabnew()
  if cwd then
    vim.cmd.tcd(vim.fn.fnameescape(cwd))
  elseif vim.startswith(path, paths.root) then
    vim.cmd.tcd(vim.fn.fnameescape(paths.root))
  end
  vim.cmd.edit(vim.fn.fnameescape(path))
end

local function set_cwd(path)
  vim.cmd.tcd(vim.fn.fnameescape(path))
  vim.notify('Changed tab working directory to ' .. path, vim.log.levels.INFO)
end

local function add_checkbox(lines, text)
  table.insert(lines, '- [ ] ' .. text)
end

local function render_tutor()
  local paths = ensure_workspace()
  local lines = {}
  local actions = {}

  local function add(line, action)
    table.insert(lines, line)
    if action then
      actions[#lines] = action
    end
  end

  add('# Kickstart Tutor')
  add('')
  add('A `vimtutor`-style session for your current Kickstart config.')
  add('Action lines open practice files in a new tab so this guide stays available.')
  add('Press `<CR>` on action lines, `x` on checklist items, `R` to rebuild the workspace, and `q` to close this buffer.')
  add('Workspace root: ' .. paths.root)
  add('')
  add('> Set cwd to tutorial workspace', function()
    set_cwd(paths.root)
  end)
  add('> Rebuild tutorial workspace', function()
    build_workspace()
    render_tutor()
  end)
  add('')
  add('## 00-10 Movement Refresh')
  add('> Open movement drill', function()
    open_file(paths.movement, paths.root)
  end)
  add('  ' .. paths.movement)
  add_checkbox(lines, 'Use `f`, `F`, `t`, and `T` on the punctuation runway in lines 3-7.')
  add_checkbox(lines, 'Use `;` and `,` to repeat your last `f` or `t` motion without retyping it.')
  add_checkbox(lines, 'Use `%` on the bracket lines to bounce across nested pairs.')
  add_checkbox(lines, 'Use `*`, `#`, `n`, and `N` on `Greeter` and `terminal-pro`.')
  add_checkbox(lines, "Set mark `a` on `MARK-A`, jump to `MARK-B`, then return with `'a` and `` `a``.")
  add_checkbox(lines, 'Create a jumplist trail with `gg`, `10G`, `/MARK-B`, and travel back with `<C-o>` then forward with `<C-i>`.')
  add('')
  add('## 10-20 Editing Fluency')
  add('> Open editing drill', function()
    open_file(paths.editing, paths.root)
  end)
  add('  ' .. paths.editing)
  add_checkbox(lines, 'Use `ci\"` on `quote_1`, then repeat the same edit on the next quoted lines with `.`.')
  add_checkbox(lines, 'Use `da(` on `delete_me` and `da[` on `delete_me_too` so you feel the difference between inside and around.')
  add_checkbox(lines, 'Use a text object like `ciw`, `ci\"`, or `dap` instead of selecting text manually.')
  add_checkbox(lines, 'Yank `phoenix` into register `a` and paste it into `slot_one` and `slot_two` with `\"a`.')
  add_checkbox(lines, 'Record a macro that changes `pending` to `done`, then replay it down the TODO block.')
  add_checkbox(lines, 'Use `mini.surround`: `saiw)` on `surround`, then `sr)\"` or `sd)` to replace or remove it.')
  add('')
  add('## 20-30 Project Navigation')
  add('> Open workspace README', function()
    open_file(paths.readme, paths.root)
  end)
  add('> Open navigation notes', function()
    open_file(paths.notes, paths.root)
  end)
  add('> Open Java app entrypoint', function()
    open_file(paths.java_app, paths.java_root)
  end)
  add('  ' .. paths.root)
  add_checkbox(lines, 'Run `\\` to reveal the current file in Neo-tree and `<leader>e` to toggle the tree.')
  add_checkbox(lines, 'Use `<leader><leader>` to switch buffers after opening at least three files from this workspace.')
  add_checkbox(lines, 'Use `<leader>sf` to fuzzy-find `Greeter.java` from the workspace root.')
  add_checkbox(lines, 'Use `<leader>sg` to live-grep for `clockwork`, `ember-fox`, or `terminal-pro`.')
  add_checkbox(lines, 'Use `gO` in `App.java` and `gW` from anywhere in the Java project to inspect symbols.')
  add('')
  add('## 30-40 Code Intelligence')
  add('> Open Greeter.java', function()
    open_file(paths.java_greeter, paths.java_root)
  end)
  add('> Open App.java', function()
    open_file(paths.java_app, paths.java_root)
  end)
  add('> Open GreeterTest.java', function()
    open_file(paths.java_test, paths.java_root)
  end)
  add_checkbox(lines, 'Use `grd` on `Greeter` or `messageFor`, then return with `<C-o>`.')
  add_checkbox(lines, 'Use `grr` on `messageFor` and inspect references in `App.java` and `GreeterTest.java`.')
  add_checkbox(lines, 'Use `grn` to rename `messageFor` to `buildMessage`, then rename it back.')
  add_checkbox(lines, 'Place the cursor on the unused `ArrayList` import in `App.java` and trigger `gra` to inspect code actions.')
  add_checkbox(lines, 'Use `[d`, `]d`, and `<leader>q` on the warning diagnostics, then compare with `:vimgrep /Greeter/ **/*.java | copen`.')
  add_checkbox(lines, 'Use `<leader>f` to format a Java buffer, then `:copen` or `:lopen` to inspect quickfix and location list windows.')
  add('')
  add('## 40-50 Git And Debugging')
  add('> Open git demo file', function()
    open_file(paths.git_demo, paths.root)
  end)
  add('> Open Java main for debugging', function()
    open_file(paths.java_app, paths.java_root)
  end)
  add_checkbox(lines, 'Use `]c` and `[c` in `40-git-demo.txt` to move across the generated hunks.')
  add_checkbox(lines, 'Use `<leader>hp` to preview a hunk, `<leader>hs` to stage it, and `<leader>hu` to undo the staged hunk.')
  add_checkbox(lines, 'Set a breakpoint with `<leader>b` on the `println` line in `App.java`.')
  add_checkbox(lines, 'Use `<F5>` to continue, `<F2>` to step over, `<F1>` to step into, and `<F3>` to step out.')
  add_checkbox(lines, 'Use `<F7>` to toggle the DAP UI while the session is running.')
  add('')
  add('## 50-60 Java Drill')
  add('> Open Java project root', function()
    open_file(paths.java_app, paths.java_root)
  end)
  add_checkbox(lines, 'Use `<leader>jC` and open `java.lang.String` or `java.util.ArrayList`.')
  add_checkbox(lines, 'Use `grn` to rename `Greeter` or `enthusiasticMessageFor`, then undo or rename it back cleanly.')
  add_checkbox(lines, 'Use `<leader>jo` in `App.java` to organize imports and remove the unused `ArrayList` import.')
  add_checkbox(lines, 'Use `<leader>jc` in `App.java` to debug the main class from the terminal.')
  add_checkbox(lines, 'Use `<leader>jn` inside `GreeterTest.java` to debug the nearest test method.')
  add('')
  add('## Daily Loop')
  add_checkbox(lines, 'Spend 5 minutes on motion-only editing in `00-movement.txt`.')
  add_checkbox(lines, 'Spend 5 minutes on search, buffers, Neo-tree, and symbols in the workspace.')
  add_checkbox(lines, 'Spend 5 minutes on one real refactor or debug session in the Java project.')

  local buf = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_set_current_buf(buf)
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, lines)
  vim.bo[buf].buftype = 'nofile'
  vim.bo[buf].bufhidden = 'wipe'
  vim.bo[buf].swapfile = false
  vim.bo[buf].filetype = 'markdown'
  vim.bo[buf].modifiable = false
  vim.api.nvim_buf_set_name(buf, 'kickstart://tutor/' .. buf)
  vim.api.nvim_buf_add_highlight(buf, -1, 'Title', 0, 0, -1)

  state.actions[buf] = actions
  vim.api.nvim_create_autocmd('BufWipeout', {
    buffer = buf,
    callback = function()
      state.actions[buf] = nil
    end,
  })

  vim.keymap.set('n', '<CR>', function()
    local current = vim.api.nvim_win_get_cursor(0)[1]
    local action = state.actions[buf][current]
    if action then
      action()
    end
  end, { buffer = buf, desc = 'Kickstart Tutor: run action' })

  vim.keymap.set('n', 'x', function()
    local current = vim.api.nvim_win_get_cursor(0)[1]
    local line = vim.api.nvim_buf_get_lines(buf, current - 1, current, false)[1]
    if not line then
      return
    end
    local replacement
    if line:find('%- %[ %] ', 1, false) == 1 then
      replacement = line:gsub('%- %[ %] ', '- [x] ', 1)
    elseif line:find('%- %[x%] ', 1, false) == 1 then
      replacement = line:gsub('%- %[x%] ', '- [ ] ', 1)
    end
    if replacement then
      vim.bo[buf].modifiable = true
      vim.api.nvim_buf_set_lines(buf, current - 1, current, false, { replacement })
      vim.bo[buf].modifiable = false
    end
  end, { buffer = buf, desc = 'Kickstart Tutor: toggle checkbox' })

  vim.keymap.set('n', 'R', function()
    build_workspace()
    render_tutor()
  end, { buffer = buf, desc = 'Kickstart Tutor: rebuild workspace' })

  vim.keymap.set('n', 'q', function()
    vim.cmd.close()
  end, { buffer = buf, desc = 'Kickstart Tutor: close buffer' })
end

function M.open()
  vim.cmd.tabnew()
  render_tutor()
end

function M.reset_workspace()
  build_workspace()
end

function M.setup()
  if vim.g.kickstart_tutor_loaded then
    return
  end
  vim.g.kickstart_tutor_loaded = true

  vim.api.nvim_create_user_command('KickstartTutor', function()
    M.open()
  end, { desc = 'Open the Kickstart interactive tutor' })

  vim.api.nvim_create_user_command('KickstartTutorReset', function()
    M.reset_workspace()
    vim.notify('Kickstart Tutor workspace rebuilt', vim.log.levels.INFO)
  end, { desc = 'Rebuild the Kickstart tutorial workspace' })
end

return M
